import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#ffffff",
    padding: 30,
    fontFamily: "Helvetica", // Standard PDF font
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#112233",
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold", // Helvetica-Bold
    marginBottom: 10,
    color: "#112233",
  },
  author: {
    fontSize: 12,
    color: "#666666",
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 15,
    marginBottom: 10,
    color: "#333333",
    backgroundColor: "#f0f0f0", // Subtle gray background for section headers
    padding: 5,
  },
  moduleContainer: {
    marginBottom: 15,
  },
  moduleTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 5,
  },
  text: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "#333333",
    marginBottom: 5,
    textAlign: "justify",
  },
  quizContainer: {
    marginTop: 30,
    borderTopWidth: 1,
    borderTopColor: "#cccccc",
    paddingTop: 20,
  },
  question: {
    fontSize: 12,
    fontWeight: "bold",
    marginTop: 10,
    marginBottom: 5,
  },
  option: {
    fontSize: 11,
    marginLeft: 10,
    color: "#555555",
  },
  correctAnswer: {
    fontSize: 11,
    marginLeft: 10,
    color: "#008000", // Green for the answer key
    fontWeight: "bold",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: "center",
    fontSize: 10,
    color: "grey",
  },
});

export default function CoursePdfDocument({ course }: any) {
  return (
    <Document>
      <Page size={"A4"} style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{course?.courseName}</Text>
          <Text style={styles.author}>Created by : {course?.user?.name}</Text>
          {/* <Text style={{ fontSize: 10, color: "#888" }}>
            Generated by CourseBuilder AI
          </Text> */}
        </View>
        <View>
          <Text style={styles.sectionTitle}>Course Modules</Text>
          {course?.modules?.map((module: any, index: number) => {
            return (
              <View key={module.moduleId} style={styles.moduleContainer}>
                <Text style={styles.moduleTitle}>
                  Module {index + 1} : {module?.title}
                </Text>
                <Text style={styles.text}>{module?.description}</Text>
              </View>
            );
          })}
        </View>
        {course?.quiz && course?.quiz?.questions && (
          <View style={styles.quizContainer} break>
            <Text style={styles.sectionTitle}>Course Quiz</Text>
            {course?.quiz?.questions?.map((q: any, index: number) => (
              <View
                key={q?.questionId || `question-${index}`}
                style={{ marginBottom: 10 }}
                wrap={false}
              >
                <Text style={styles.question}>
                  Q{index + 1}: {q.question}
                </Text>
                {q.options.map((opt: any, i: number) => (
                  <Text key={opt} style={styles.option}>
                    • {opt}
                  </Text>
                ))}
                <Text style={styles.correctAnswer}>Answer: {q.answer}</Text>
              </View>
            ))}
          </View>
        )}
        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `${pageNumber} / ${totalPages}`
          }
          fixed
        />
      </Page>
    </Document>
  );
}
